# Generated by Django 3.2.9 on 2021-11-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przewoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=15)),
                ('client', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('wage_without_car', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='Pub date')),
            ],
        ),
    ]
